version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:5001/api
    depends_on:
      - server

  mongodb:
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=surfing
      - MONGO_INITDB_ROOT_PASSWORD=rocks
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=surfing
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rocks
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
