version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - server
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
      - "9229:9229"
    links:
      - mongo
    volumes:
      - ./server:/app

  mongo:
    container_name: mongo
    image: mongo:5.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=surfing
      - MONGO_INITDB_ROOT_PASSWORD=rocks
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=surfing
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rocks
