services:
  - type: web
    name: lsp-client
    env: static
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_URL
      - key: REACT_APP_AUTH0_DOMAIN
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_AUTH0_DOMAIN
      - key: REACT_APP_AUTH0_CLIENT_ID
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_AUTH0_CLIENT_ID
      - key: REACT_APP_AUTH0_AUDIENCE
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_AUTH0_AUDIENCE
      - key: REACT_APP_SWELL_DATA_API_KEY
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_SWELL_DATA_API_KEY
      - key: REACT_APP_AUTH0_DOMAIN
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_AUTH0_DOMAIN
  - type: web
    name: lsp-api
    env: docker
    rootDir: server
    region: singapore
    envVars:
      - key: API_PORT
        value: 80
      - key: DATABASE_URL
        # value: mongodb://surfing:rocks@mongo:27017/lsp?authSource=admin
        value: mongodb+srv://surfing:rocks@lsp-cluster.sdi2n.mongodb.net/
    plan: free
  - type: pserv
    name: lsp-mongodb
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
